# Generated by Django 5.2.3 on 2025-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type_dish',
            field=models.CharField(choices=[('salad', 'Salad'), ('soup', 'Soup'), ('main', 'Main'), ('dessert', 'Dessert')], max_length=50),
        ),
    ]
