# Generated by Django 5.2.3 on 2025-07-10 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rating_unique_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='rating',
            name='publication_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='publication_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
