# Generated by Django 5.2.3 on 2025-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_rating_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(choices=[('1-5 minutes', 'One Five Minutes'), ('5-10 minutes', 'Five Ten Minutes'), ('10-15 minutes', 'Ten Fifteen Minutes'), ('15-20 minutes', 'Fifteen Twenty Minutes'), ('20-30 minutes', 'Twenty Thirty Minutes'), ('30-45 minutes', 'Thirty Fortyfive Minutes'), ('45-60 minutes', 'Fourtyfive Sixty Minutes')], default='1-5 minutes', max_length=50),
        ),
    ]
