# Generated by Django 5.2.3 on 2025-07-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Meat & Fish', 'Meat Fish'), ('Dairy & Eggs', 'Dairy Eggs'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains & Cereals', 'Grains Cereals'), ('Oils & Fats', 'Oils Fats'), ('Spices & Seasonings', 'Spices Seasonings')], default='Meat & Fish', max_length=100),
        ),
    ]
