# Generated by Django 5.2.3 on 2025-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(choices=[('1_5_minutes', '1-5 minutes'), ('5-10 minutes', 'Five Ten Minutes'), ('10-15 minutes', 'Ten Fifteen Minutes'), ('15-20 minutes', 'Fifteen Twenty Minutes'), ('20-30 minutes', 'Twenty Thirty Minutes'), ('30-45 minutes', 'Thirty Fortyfive Minutes'), ('45-60 minutes', 'Fourtyfive Sixty Minutes')], default='1_5_minutes', max_length=50),
        ),
    ]
