# Generated by Django 5.2.3 on 2025-07-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
